TEXTO_ANAMNESIS="MOTIVO DE CONSULTA: 

ANAMNESIS: 
-    ANTECEDENTES MÉDICOS GENERALES: 
-    ANTECEDENTES SICOSOCIALES: 
-    HÁBITOS: 
-
EXAMEN DEL CUARTO SUPERIOR: 

EXAMEN FACIAL: 

EXAMEN DE LAXITUD LIGAMENTARIA (TEST DE BEIGHTON): 

EXAMEN NEUROMUSCULAR DERECHO: 

EXAMEN NEUROMUSCULAR IZQUIERDO: 

EXAMEN DE ARTICULACIÓN DERECHA: 

EXAMEN DE ARTICULACIÓN IZQUIERDA: 

EXAMEN OCLUSAL: 

TRATAMIENTO: 

OBSERVACIONES: 
 "
