# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e80ea2ef31c8dc37b22218937daca4ce04520496e106228cc5c07752b30c546f3de87c3208c3ff746f84d502258ffbb46185592a200284f48248b637a80249

test:
  secret_key_base: 242a1089742060cc97b11d1a790659e52cfee0851d79f0b873cb1ad8f6fa5f45d8448199ca95162bd3607fbe4c02e20823b19c83e86c9feb3a414165390b30ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
